modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
issueTrackerURL="https://github.com/Rexbas/Bouncing-Balls/issues"
logoFile="logo.png"
[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
updateJSONURL="https://forge.curseupdate.com/246030/bouncingballs"
displayURL="https://www.curseforge.com/minecraft/mc-mods/bouncing-balls"
authors="${mod_authors}"
description='''${mod_description}'''
[[dependencies.${mod_id}]]
    modId="neoforge"
    mandatory=true
    versionRange="${neo_version_range}"
    ordering="NONE"
    side="BOTH"
[[dependencies.${mod_id}]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"
[[dependencies.${mod_id}]]
    modId="bouncingballs_api"
    mandatory=true
    versionRange="${boucing_balls_api_version_range}"
    ordering="AFTER"
    side="BOTH"